### ISSUE TITLE
server 3.0 

### ISSUE THREAD

**Issue by bunnyblue** [actorapp/actor-platform#1005]
CentOS 7
postgresql 9.4
 
user actor is connected bu pgAdmin

nohup.out log is here

`
org.postgresql.util.PSQLException: 致命错误: 用户 "actor" Ident 认证失败
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:433) ~[org.postgresql.postgresql-9.4.1208.jar:9.4.1208]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:208) ~[org.postgresql.postgresql-9.4.1208.jar:9.4.1208]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:67) ~[org.postgresql.postgresql-9.4.1208.jar:9.4.1208]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216) ~[org.postgresql.postgresql-9.4.1208.jar:9.4.1208]
	at org.postgresql.Driver.makeConnection(Driver.java:406) ~[org.postgresql.postgresql-9.4.1208.jar:9.4.1208]
	at org.postgresql.Driver.connect(Driver.java:274) ~[org.postgresql.postgresql-9.4.1208.jar:9.4.1208]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[com.zaxxer.HikariCP-2.4.6.jar:na]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[com.zaxxer.HikariCP-2.4.6.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:316) ~[com.zaxxer.HikariCP-2.4.6.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:173) ~[com.zaxxer.HikariCP-2.4.6.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:443) [com.zaxxer.HikariCP-2.4.6.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:66) [com.zaxxer.HikariCP-2.4.6.jar:na]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:568) [com.zaxxer.HikariCP-2.4.6.jar:na]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:561) [com.zaxxer.HikariCP-2.4.6.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
 DEBUG com.zaxxer.hikari.pool.HikariPool     - Cannot acquire connection from data source
`

**Comment by rockjam** [comment]
Auth error I guess, make sure you can connect to database you have with credentials you use to connect in server.conf

**Comment by bunnyblue** [comment]
solved ,ip error
