### ISSUE TITLE
FATAL: database "actor" does not exist

### ISSUE THREAD

**Issue by narychen** [actorapp/actor-platform#146]
I built the actor-server on my own and start it from sbt run.
Got the database missing error.
Only found some sql.migration scripts.
How can I import the actor database into postgresql?

error as below--->

22:21:35.170 [HikariCP connection filler (pool main)] DEBUG com.zaxxer.hikari.pool.PoolUtilities - Closing connection null
22:21:35.266 [HikariCP connection filler (pool main)] DEBUG com.zaxxer.hikari.pool.HikariPool - Connection attempt to database main failed: FATAL: database "actor" does not exist
org.postgresql.util.PSQLException: FATAL: database "actor" does not exist
	at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:684) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:199) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:127) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:41) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.Driver.makeConnection(Driver.java:414) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.Driver.connect(Driver.java:282) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:62) ~[HikariCP-2.3.5.jar:na]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:68) ~[HikariCP-2.3.5.jar:na]
	at com.zaxxer.hikari.pool.BaseHikariPool.addConnection(BaseHikariPool.java:410) ~[HikariCP-2.3.5.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.lambda$addBagItem$2(HikariPool.java:75) [HikariCP-2.3.5.jar:na]
	at com.zaxxer.hikari.pool.HikariPool$$Lambda$30/743437792.run(Unknown Source) [HikariCP-2.3.5.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]

**Comment by prettynatty** [comment]
You need to create database in postgres and set it in server.conf.

**Comment by narychen** [comment]
Do I need to create the related tables or just need to create the actor database in postgres?

**Comment by prettynatty** [comment]
no, they will be created automatically

**Comment by narychen** [comment]
After create the actor dababase, got the logging as below. Is it correct ?

13:30:46.454 [Hikari Housekeeping Timer (pool main)] DEBUG com.zaxxer.hikari.pool.HikariPool - Before cleanup pool stats main (total=8, inUse=0, avail=8, waiting=0)
13:30:46.454 [Hikari Housekeeping Timer (pool main)] DEBUG com.zaxxer.hikari.pool.HikariPool - After cleanup pool stats main (total=8, inUse=0, avail=8, waiting=0)
13:31:16.451 [Hikari Housekeeping Timer (pool main)] DEBUG com.zaxxer.hikari.pool.HikariPool - Before cleanup pool stats main (total=8, inUse=0, avail=8, waiting=0)
13:31:16.452 [Hikari Housekeeping Timer (pool main)] DEBUG com.zaxxer.hikari.pool.HikariPool - After cleanup pool stats main (total=8, inUse=0, avail=8, waiting=0)
13:31:28.907 [actor-server-akka.actor.default-dispatcher-2] DEBUG s.backend.DatabaseComponent.action - #1: result [select s21."id" from "groups" s21]
13:31:28.908 [AsyncExecutor.default-19] DEBUG slick.jdbc.JdbcBackend.statement - Preparing statement: select s21."id" from "groups" s21
13:31:28.909 [AsyncExecutor.default-19] DEBUG slick.jdbc.JdbcBackend.benchmark - Execution of prepared statement took 504µs
13:31:28.909 [AsyncExecutor.default-19] DEBUG slick.jdbc.StatementInvoker.result - /----\
13:31:28.909 [AsyncExecutor.default-19] DEBUG slick.jdbc.StatementInvoker.result - | 1  |
13:31:28.909 [AsyncExecutor.default-19] DEBUG slick.jdbc.StatementInvoker.result - | id |
13:31:28.909 [AsyncExecutor.default-19] DEBUG slick.jdbc.StatementInvoker.result - |----|
13:31:28.909 [AsyncExecutor.default-19] DEBUG slick.jdbc.StatementInvoker.result - \----/
13:31:46.450 [Hikari Housekeeping Timer (pool main)] DEBUG com.zaxxer.hikari.pool.HikariPool - Before cleanup pool stats main (total=8, inUse=0, avail=8, waiting=0)
13:31:46.451 [Hikari Housekeeping Timer (pool main)] DEBUG com.zaxxer.hikari.pool.HikariPool - After cleanup pool stats main (total=8, inUse=0, avail=8, waiting=0)

**Comment by narychen** [comment]
The same log prints again and again indefinitely

**Comment by prettynatty** [comment]
It is ok

**Comment by narychen** [comment]
Oh, Thanks a lot.
I'm reading the code.
Scala's implicit conversion hell is realy tough.
I'm just wondering why not use java directly.

**Comment by prettynatty** [comment]
User data is important. Performance is important. Reliability is important.
Scala lets us write safe, performant and self-healing server modules without java's boilerplate and error-prone code.
Did you ever seen NullPointerExceptions? During working on Actor Server, I didn't.

**Comment by ex3ndr** [comment]
Java produces ALOT of code. This is not useful for concurrent project.
