### ISSUE TITLE
error building web-app

### ISSUE THREAD

**Issue by JamieDavis** [actorapp/actor-platform#155]
Hi, trying to build the web app on Ubuntu server 14.04, getting as far the the "gulp dev" and i am getting the below error, any help is gratefully received.

root@hq:~/actor-platform/actor-apps/app-web# gulp build --release
[21:13:16] Requiring external module babel-core/register

/root/actor-platform/actor-apps/app-web/gulpfile.babel.js:3
import webpack from 'webpack';
^^^^^^
SyntaxError: Unexpected reserved word
at Module._compile (module.js:439:25)
at loader (/root/actor-platform/actor-apps/app-web/node_modules/babel-core/lib/api/register/node.js:136:5)
at Object.require.extensions.(anonymous function) [as .js] (/root/actor-platform/actor-apps/app-web/node_modules/babel-core/lib/api/register/node.js:146:7)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

**Comment by prettynatty** [comment]
Try
```
npm install -g npm
npm install -g gulp
```

**Comment by JamieDavis** [comment]
Hi guys, 

I've tried that, and also olegshilov has had ago at doing it aswell with SSH Access with a fresh copy of Ubuntu 14.04 installed

Not sure what else to try

**Comment by olegshilov** [comment]
I found out that one of the NPM modules depends on python, make, g++, bzip2 which is not been installed on @JamieDavis system.

To fix that they must be installed with: `apt-get install python make g++ bzip2`
