### ISSUE TITLE
The server will down after 1 day running

### ISSUE THREAD

**Issue by ljshj** [actorapp/actor-platform#220]
09:32:15.494UTC ERROR akka.actor.ActorSystemImpl akka.actor.ActorSystemImpl(actor-server)   Websocket handler failed while waiting for handler completion with empty.head
java.lang.UnsupportedOperationException: empty.head
        at scala.collection.immutable.Vector.head(Vector.scala:193) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at akka.http.impl.engine.ws.Websocket$$anonfun$2.apply(Websocket.scala:90) ~[com.typesafe.akka.akka-http-core-experimental_2.11-2.0.1.jar:na]
        at akka.http.impl.engine.ws.Websocket$$anonfun$2.apply(Websocket.scala:89) ~[com.typesafe.akka.akka-http-core-experimental_2.11-2.0.1.jar:na]
        at akka.stream.impl.fusing.Map.onPush(Ops.scala:27) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.1.jar:na]
        at akka.stream.impl.fusing.Map.onPush(Ops.scala:26) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.1.jar:na]
        at akka.stream.stage.AbstractStage$PushPullGraphLogic$$anon$1.onPush(Stage.scala:54) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.1.jar:na]
        at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:575) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.1.jar:na]
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:617) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.1.jar:na]
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:533) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.1.jar:na]
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:445) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.1.jar:na]
        at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:400) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.1.jar:na]
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:547) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.1.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[com.typesafe.akka.akka-actor_2.11-2.4.0.jar:na]
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:495) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.1.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:525) [com.typesafe.akka.akka-actor_2.11-2.4.0.jar:na]
        at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:494) [com.typesafe.akka.akka-actor_2.11-2.4.0.jar:na]
        at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1) [com.typesafe.akka.akka-actor_2.11-2.4.0.jar:na]
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) [org.aspectj.aspectjweaver-1.8.7.jar:1.8.7]
        at akka.kamon.instrumentation.ActorCellInstrumentation$$anonfun$aroundBehaviourInvoke$1.apply(ActorCellInstrumentation.scala:63) [io.kamon.kamon-akka_2.11-0.5.2.jar:0.5.2]
        at kamon.trace.Tracer$.withContext(TracerModule.scala:53) [io.kamon.kamon-core_2.11-0.5.2.jar:0.5.2]
        at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorCellInstrumentation.scala:62) [io.kamon.kamon-akka_2.11-0.5.2.jar:0.5.2]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [com.typesafe.akka.akka-actor_2.11-2.4.0.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [com.typesafe.akka.akka-actor_2.11-2.4.0.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:224) [com.typesafe.akka.akka-actor_2.11-2.4.0.jar:na]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [com.typesafe.akka.akka-actor_2.11-2.4.0.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.7.jar:na]
09:41:44.515UTC WARN  akka.actor.ActorSystemImpl akka.actor.ActorSystemImpl(actor-server)   Transport package length is more than expected

**Comment by prettynatty** [comment]
It's an Akka Streams bug akka/akka#19398
