### ISSUE TITLE
No values retrieved from database before restart

### ISSUE THREAD

**Issue by vaibhav-46** [actorapp/actor-platform#285]
Multi device sync does not work. Push notifications do not work.

Scenario : The server is running and a new user is registered. He registers on one device and sends a few messages. Then he registers on another device with the same number. After the old messages sent are loaded, any new messages are not synced between devices and neither are Push Notifications sent on any of the device.

Some debugging done : I added some log statements to the server to see if I could figure out what the issue was. I found that data is not being loaded from the database before the server restarts. For example, in the VendorPush.scala file when the deliver function is called, mapping variable is empty and does not contain any of the push details. Similarly, I added a log statement in the UpdatesConsumer in the case NewUpdate and the authSid is 0 for the client. 

Once the server is restarted, this problem disappears. If there are any logs that you would like me to provide, do let me know.

**Comment by prettynatty** [comment]
Thanks for detailed debug info, I'll check it out soon.

**Comment by vaibhav-46** [comment]
I managed to debug the push notifications issue. On starting the server and a new device connecting, I get an error as follows : 

 AuthSession not found
java.lang.RuntimeException: AuthSession not found
    at im.actor.server.sequence.SeqUpdatesExtension.im$actor$server$sequence$SeqUpdatesExtension$$$anonfun$11(SeqUpdatesExtension.scala:212) ~[im.actor.server.actor-core-1.0.78-SNAPSHOT.jar:1.0.78-SNAPSHOT]
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[org.scala-lang.scala-library-2.11.7.jar:na]
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[org.scala-lang.scala-library-2.11.7.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run_aroundBody0(Promise.scala:32) ~[org.scala-lang.scala-library-2.11.7.jar:na]
    at scala.concurrent.impl.CallbackRunnable$AjcClosure1.run(Promise.scala:1) ~[org.scala-lang.scala-library-2.11.7.jar:na]
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[org.aspectj.aspectjweaver-1.8.7.jar:1.8.7]
    at kamon.scala.instrumentation.FutureInstrumentation$$anonfun$aroundExecution$1.apply(FutureInstrumentation.scala:44) ~[io.kamon.kamon-scala_2.11-0.5.2.jar:0.5.2]
    at kamon.trace.Tracer$.withContext(TracerModule.scala:53) ~[io.kamon.kamon-core_2.11-0.5.2.jar:0.5.2]
    at kamon.scala.instrumentation.FutureInstrumentation.aroundExecution(FutureInstrumentation.scala:43) ~[io.kamon.kamon-scala_2.11-0.5.2.jar:0.5.2]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:31) ~[org.scala-lang.scala-library-2.11.7.jar:na]
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) ~[com.typesafe.akka.akka-actor_2.11-2.4.0.jar:na]
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) ~[com.typesafe.akka.akka-actor_2.11-2.4.0.jar:na]
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[com.typesafe.akka.akka-actor_2.11-2.4.0.jar:na]
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[com.typesafe.akka.akka-actor_2.11-2.4.0.jar:na]
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) ~[org.scala-lang.scala-library-2.11.7.jar:na]
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) ~[com.typesafe.akka.akka-actor_2.11-2.4.0.jar:na]


This is because when the push credentials are sent, the server expects AuthSessionRepo to be filled. But since there is only authId present at the moment, there is no authSession and hence the credentials are not stored. When you restart the server, it picks up the data from the database and hence it works then.
