### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded 

### ISSUE THREAD

**Issue by ljshj** [actorapp/actor-platform#324]
actor-1.0.112-SNAPSHOT

java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to java_pid29391.hprof ...
Heap dump file created [1611576989 bytes in 19.613 secs]
Uncaught error from thread [actor-server-akka.actor.default-dispatcher-15072] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[actor-server]
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at akka.dispatch.Envelope$.apply(AbstractDispatcher.scala:27)
        at akka.actor.Cell$class.sendMessage(ActorCell.scala:294)
        at akka.actor.ActorCell.sendMessage(ActorCell.scala:373)
        at akka.actor.RepointableActorRef.$bang(RepointableActorRef.scala:166)
        at akka.stream.impl.fusing.GraphInterpreterShell$$anonfun$interpreter$1.apply(ActorGraphInterpreter.scala:323)
        at akka.stream.impl.fusing.GraphInterpreterShell$$anonfun$interpreter$1.apply(ActorGraphInterpreter.scala:323)
        at akka.stream.stage.GraphStageLogic$$anon$2.invoke(GraphStage.scala:937)
        at akka.stream.stage.TimerGraphStageLogic$$anon$3.run(GraphStage.scala:1234)
        at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(Scheduler.scala:257)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:399)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by prettynatty** [comment]
waiting for fix in akka/akka#19398

**Comment by liruqi** [comment]
@prettynatty akka/akka#19398 is closed now. Have Actor server updated akka?
