### ISSUE TITLE
Error upon pod install

### ISSUE THREAD

**Issue by mmosix** [actorapp/actor-platform#386]
pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing BlockAlertsAnd-ActionSheets (1.0.6)
Installing BrightFutures (3.3.0)
Installing Cartography (0.6.0)
Installing CocoaAsyncSocket (7.4.3)
Installing Crashlytics (3.7.0)

[!] Error installing Crashlytics

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6e6c9796ba248d6070758c1296aa8aaa12f3834e
```

### Plugins

```

```

### Podfile

```ruby
platform :ios, '8.0'
use_frameworks!

workspace 'ActorSDK'
xcodeproj 'ActorSDK.xcodeproj'
xcodeproj 'ActorApp.xcodeproj'

inhibit_all_warnings!

link_with 'ActorApp'

target 'ActorApp' do
    xcodeproj 'ActorApp.xcodeproj'
    
    # Tracking
    pod 'HockeySDK', '~> 3.8-RC'
    pod 'Fabric'
    pod 'Crashlytics'

    # Core Tools
    pod 'RegexKitLite'
    pod 'CocoaAsyncSocket'
    pod 'zipzap'
    pod 'YYKit'
    pod 'BrightFutures'

    # Main UI
    pod 'TTTAttributedLabel'
    pod 'RSKImageCropper'
    pod 'JDStatusBarNotification'
    pod 'Neon'
    pod 'Cartography'
    pod 'PureLayout'

    # Small UI
    pod 'VBFPopFlatButton'
    pod 'SZTextView'
        
    # Progress
    pod 'M13ProgressSuite'
    pod 'MBProgressHUD'
    pod 'SVProgressHUD'

    # Alerts
    pod 'BlockAlertsAnd-ActionSheets'
    pod 'RMUniversalAlert'
    pod 'PSTAlertController'
    
    # Calls
    # pod 'libjingle_peerconnection'
end

target 'ActorSDK' do
    xcodeproj 'ActorSDK.xcodeproj'

    # J2Objc Runtime
    pod 'J2ObjC-Framework'

    # Core Tools
    pod 'RegexKitLite'
    pod 'CocoaAsyncSocket'
    pod 'zipzap'
    pod 'YYKit'
    pod 'BrightFutures'
    pod 'Cartography'
    pod 'PureLayout'

    # Main UI
    pod 'TTTAttributedLabel'
    pod 'RSKImageCropper'
    pod 'JDStatusBarNotification'

    # Small UI
    pod 'VBFPopFlatButton'
    pod 'SZTextView'
        
    # Progress
    pod 'M13ProgressSuite'
    pod 'MBProgressHUD'
    pod 'SVProgressHUD'

    # Alerts
    pod 'BlockAlertsAnd-ActionSheets'
    pod 'RMUniversalAlert'
    pod 'PSTAlertController'
    
    # Calls
    pod 'libjingle_peerconnection'
end
```

### Error

```
NameError - uninitialized constant Pod::Downloader::Http::URI
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/http.rb:54:in `type_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/http.rb:32:in `type'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/http.rb:21:in `download!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/base.rb:80:in `block in download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:145:in `block in ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:144:in `ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/base.rb:78:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:110:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:65:in `download_request'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:170:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:153:in `block in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:180:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:180:in `in_tmpdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:152:in `uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:34:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:113:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:53:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:339:in `install_source_of_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:306:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:305:in `block in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:297:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:297:in `install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:146:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:144:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:106:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=uninitialized+constant+Pod%3A%3ADownloader%3A%3AHttp%3A%3AURI&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

**Comment by mmosix** [comment]
uninstalling and re-installing cocopods solved the issue
