### ISSUE TITLE
User should be able to edit his last message unless the new message by other person was sent

### ISSUE THREAD

**Issue by Maay** [actorapp/actor-platform#670]
If last message in message list  is mine then in it's menu should appear the "edit message" button. It should copy text in text area with cursor autofocus.
Same should happen when I'm pressing "up arrow" on keyboard with cursor in textarea and no text in field.

**Comment by nkt** [comment]
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by Maay** [comment]
Sometimes messages are impossible to edit 
```
MessageActionCreators.js:119O {f: "Current Thread doesn't have Active Dispatchers", i: null, __gwt$backingJsError: Error: Current Thread doesn't have Active Dispatchers
    at Error (native)
    at w4.S (https://app…}__gwt$backingJsError: Error: Current Thread doesn't have Active Dispatchers
    at Error (native)
    at w4.S (https://app.actor.im/app.43bd488840510097d589.js:75:5002)
    at w (https://app.actor.im/app.43bd488840510097d589.js:60:3276)
    at C (https://app.actor.im/app.43bd488840510097d589.js:60:3626)
    at O (https://app.actor.im/app.43bd488840510097d589.js:60:3671)
    at a2 (https://app.actor.im/app.43bd488840510097d589.js:74:13615)
    at B1 (https://app.actor.im/app.43bd488840510097d589.js:74:10777)
    at w4.R (https://app.actor.im/app.43bd488840510097d589.js:81:11232)
    at w4.we (https://app.actor.im/app.43bd488840510097d589.js:81:10525)
    at https://app.actor.im/app.43bd488840510097d589.js:73:27739
    at new _ (https://app.actor.im/app.43bd488840510097d589.js:110:12510)
    at OQ (https://app.actor.im/app.43bd488840510097d589.js:73:27711)
    at w4.Gc (https://app.actor.im/app.43bd488840510097d589.js:80:31391)
    at Object.<anonymous> (https://app.actor.im/app.43bd488840510097d589.js:62:24530)
    at Object.editMessage (https://app.actor.im/app.43bd488840510097d589.js:74:28736)
    at e.editMessage (https://app.actor.im/app.43bd488840510097d589.js:2:1432)
    at e.endEdit (https://app.actor.im/app.43bd488840510097d589.js:10:21343)
    at t.onEdit (https://app.actor.im/app.43bd488840510097d589.js:96:1449)
    at t.onSubmit (https://app.actor.im/app.43bd488840510097d589.js:96:17421)
    at t.onKeyDown (https://app.actor.im/app.43bd488840510097d589.js:31:13961)
    at Object.r (https://app.actor.im/app.43bd488840510097d589.js:56:24332)
    at a (https://app.actor.im/app.43bd488840510097d589.js:156:8108)
    at Object.s [as executeDispatchesInOrder] (https://app.actor.im/app.43bd488840510097d589.js:156:8319)
    at f (https://app.actor.im/app.43bd488840510097d589.js:11:19241)
    at d (https://app.actor.im/app.43bd488840510097d589.js:11:19367)
    at Array.forEach (native)
    at n (https://app.actor.im/app.43bd488840510097d589.js:56:31798)
    at Object.m.processEventQueue (https://app.actor.im/app.43bd488840510097d589.js:11:20487)
    at r (https://app.actor.im/app.43bd488840510097d589.js:157:6578)
    at Object.o.handleTopLevel [as _handleTopLevel] (https://app.actor.im/app.43bd488840510097d589.js:157:6684)
    at a (https://app.actor.im/app.43bd488840510097d589.js:157:7133)
    at o (https://app.actor.im/app.43bd488840510097d589.js:157:6947)
    at r.i.perform (https://app.actor.im/app.43bd488840510097d589.js:14:9154)
    at Object.h.batchedUpdates (https://app.actor.im/app.43bd488840510097d589.js:56:20434)
    at Object.o [as batchedUpdates] (https://app.actor.im/app.43bd488840510097d589.js:9:22476)
    at g.dispatchEvent (https://app.actor.im/app.43bd488840510097d589.js:157:8023)
    at HTMLDocument.e.bugsnag (https://app.actor.im/app.43bd488840510097d589.js:109:19220)f: "Current Thread doesn't have Active Dispatchers"i: null__proto__: ObjectGg: seHg: Objectconstructor: Object__proto__: Object(anonymous function) @ MessageActionCreators.js:119a @ es6.promise.js:89(anonymous function) @ es6.promise.js:102c @ _microtask.js:18_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```
