### ISSUE TITLE
Failure in RpcApiService while handling messageId

### ISSUE THREAD

**Issue by mosqueiro** [actorapp/actor-platform#762]
This error appears in sync:

`23:31:15.244UTC ERROR i.actor.server.api.rpc.RpcApiService akka.tcp://actor-server@45.32.27.108:2552/user/rpc-api-service   Failure in RpcApiService while handling messageId: 259
java.lang.IllegalArgumentException: key not found: 5
	at scodec.Attempt$Failure.require(Attempt.scala:122) ~[org.scodec.scodec-core_2.11-1.8.1.jar:na]
	at scodec.Attempt$Failure.require(Attempt.scala:108) ~[org.scodec.scodec-core_2.11-1.8.1.jar:na]
	at im.actor.server.api.rpc.RpcApiService$$anonfun$receive$1.applyOrElse(RpcApiService.scala:47) ~[im.actor.server.actor-rpc-api-1.0.152.jar:1.0.152]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at im.actor.server.api.rpc.RpcApiService.aroundReceive(RpcApiService.scala:26) ~[im.actor.server.actor-rpc-api-1.0.152.jar:1.0.152]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.8.jar:na]`

**Comment by djjatoro** [comment]
Hi.
I have the same incidence explained and detailed here:
https://github.com/actorapp/actor-platform/issues/761
https://github.com/actorapp/actor-platform/issues/731
As a consequence the server returns the log:
06:56:14.782UTC ERROR i.actor.server.api.rpc.RpcApiService akka.tcp://actor-server@10.1.0.4:2552/user/rpc-api-service   Failure in RpcApiService while handling messageId: 61
java.lang.IllegalArgumentException: key not found: 5
        at scodec.Attempt$Failure.require(Attempt.scala:122) ~[org.scodec.scodec-core_2.11-1.8.1.jar:na]
        at scodec.Attempt$Failure.require(Attempt.scala:108) ~[org.scodec.scodec-core_2.11-1.8.1.jar:na]
        at im.actor.server.api.rpc.RpcApiService$$anonfun$receive$1.applyOrElse(RpcApiService.scala:47) ~[im.actor.server.actor-rpc-api-1.0.152.jar:1.0.152]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
        at im.actor.server.api.rpc.RpcApiService.aroundReceive(RpcApiService.scala:26) ~[im.actor.server.actor-rpc-api-1.0.152.jar:1.0.152]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:495) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:224) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.8.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.8.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.8.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.8.jar:na]
06:56:14.783UTC DEBUG im.actor.server.session.RpcHandler akka.tcp://actor-server@10.1.0.4:2552/system/sharding/Session/9/1290811915256383719_653650439187042322/rpcHandler   Received RpcResponse for messageId: 61, publishing

And

06:55:52.942UTC DEBUG i.a.s.dialog.DialogExtensionImpl DialogExtensionImpl(akka://actor-server)   No delivery extensions, using default one
06:55:52.971UTC DEBUG i.a.server.dialog.DialogProcessor akka.tcp://actor-server@10.1.0.4:2552/system/sharding/UserProcessor/68/850430568/UserPeer/Private_1369690931   Stashing message: sender_auth_sid: 478509493
random_id: 2877792889679235196
message: "\b\001\022\016\n\fBuenos d\303\255as"
is_fat: false
origin {
  type: Private
  id: 1369690931
}
dest {
  type: Private
  id: 850430568
}
date: 1461653752932
access_hash: 2143842144861914871
sender_auth_id: 1290811915256383719

06:55:52.971UTC DEBUG akka.cluster.sharding.Shard akka.tcp://actor-server@10.1.0.4:2552/system/sharding/SocialManager/31   Starting entity [1369690931] in shard [31]
06:55:52.979UTC DEBUG akka.cluster.sharding.Shard akka.tcp://actor-server@10.1.0.4:2552/system/sharding/SocialManager/68   Starting entity [850430568] in shard [68]
06:55:53.021UTC DEBUG a.h.i.e.c.PoolSlot$SlotProcessor akka.tcp://actor-server@10.1.0.4:2552/user/SlotProcessor-33   become unconnected, from subscriber pending
06:55:53.027UTC DEBUG a.h.i.e.c.PoolSlot$SlotProcessor akka.tcp://actor-server@10.1.0.4:2552/user/SlotProcessor-35   become unconnected, from subscriber pending
06:55:53.030UTC DEBUG a.h.i.e.c.PoolSlot$SlotProcessor akka.tcp://actor-server@10.1.0.4:2552/user/SlotProcessor-32   become unconnected, from subscriber pending
06:55:53.031UTC DEBUG a.h.i.e.c.PoolSlot$SlotProcessor akka.tcp://actor-server@10.1.0.4:2552/user/SlotProcessor-34   become unconnected, from subscriber pending
21:02:57.601UTC DEBUG com.zaxxer.hikari.pool.PoolElf akka.tcp://actor-server@10.1.0.4:2552/user/SlotProcessor-1   main - Reset (nothing) on connection org.postgresql.jdbc4.Jdbc4Connection@5bfe9052
06:55:53.075UTC DEBUG im.actor.server.sequence.VendorPush akka.tcp://actor-server@10.1.0.4:2552/system/sharding/SeqUpdatesManager/8/850430568/vendor-push   Notifications for peer type: Private
id: 1369690931
 are not set, push will be visible
06:55:53.075UTC WARN  i.a.s.sequence.GooglePushExtension GooglePushExtension(akka://actor-server)   Key not found for projectId: 209133700967
06:55:53.075UTC DEBUG im.actor.server.sequence.VendorPush akka.tcp://actor-server@10.1.0.4:2552/system/sharding/SeqUpdatesManager/8/850430568/vendor-push   Notifications for peer type: Private
id: 1369690931
 are not set, push will be visible
06:55:53.075UTC DEBUG im.actor.server.sequence.VendorPush akka.tcp://actor-server@10.1.0.4:2552/system/sharding/SeqUpdatesManager/8/850430568/vendor-push   Notifications for peer type: Private
id: 1369690931
 are not set, push will be visible

**Comment by rockjam** [comment]
@mosqueiro @djjatoro will check it with 1.0.152, and let you know about possible solution

**Comment by rockjam** [comment]
@mosqueiro @djjatoro I was able to reproduce it. This problem caused by newer client communicate with older server version

**Comment by rockjam** [comment]
Solution is: either downgrade clients(can't tell you exact version of client, that will handle it), or wait couple days until we make release of stable version of server

**Comment by mosqueiro** [comment]
Thank you @rockjam 
I did the downgrade to 1.0.181 (android) and it really worked.
We wait an stable version that works the voice call.

**Comment by djjatoro** [comment]
@mosqueiro: please, could you have the kindness of share with me:

1) how did you downgrade android-app from platform repo?
2) How can i know the version which i am working (old and new) in platform repo?
3) What is the process you follow to import and build the Gradle project of android- app of platform repo to compare if the way which I am doing is correct?

Thanks in advance. Greetings.

**Comment by udee297** [comment]
how do u downgrade ios app?
im facing this issue using ios

**Comment by damlaxkid** [comment]
Please how can we install this server in a clustered computer
