### ISSUE TITLE
release 1.0.152 question,about ssl

### ISSUE THREAD

**Issue by nm-cmd** [actorapp/actor-platform#824]
OpenSSL (via netty-tcnative) not available; will use JDK SSL provider.
Uncaught error from thread [actor-server-akka.actor.default-dispatcher-23] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[actor-server]
java.lang.ExceptionInInitializerError
at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:245)
at io.netty.handler.ssl.JdkSslClientContext.<init>(JdkSslClientContext.java:265)
at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:742)
at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:395)
at com.relayrides.pushy.apns.ApnsClient.getSslContextWithCertificateAndPrivateKey(ApnsClient.java:360)
at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12InputStream(ApnsClient.java:354)
at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12File(ApnsClient.java:331)
at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:234)
at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:209)

**Comment by rockjam** [comment]
@nm-cmd I'm not sure it is 1.0.152 release. You must be building actor platform from source. Anyway, to make this go away - use this installation script https://developer.actor.im/docs/prerequisites#section-updating-openssl-and-installing-libapr1

**Comment by nm-cmd** [comment]
thank you very much! I try now! but i am OS is centos 6.5,how i operation?

**Comment by rockjam** [comment]
You should find equivalent packages in your package manager, or build them from source.
