### ISSUE TITLE
Internal error translating 

### ISSUE THREAD

**Issue by abdulrauf142** [actorapp/actor-platform#842]
error: internal error translating "/ActorApp/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/**ConfigurationBuilder.java**"

java.lang.AssertionError
	at com.google.devtools.j2objc.gen.TypeGenerator.getMethodSignature(TypeGenerator.java:283)
	at com.google.devtools.j2objc.gen.TypeDeclarationGenerator.printMethodDeclaration(TypeDeclarationGenerator.java:549)
	at com.google.devtools.j2objc.gen.TypeDeclarationGenerator.printMethodDeclaration(TypeDeclarationGenerator.java:572)
	at com.google.devtools.j2objc.gen.TypeGenerator.printDeclaration(TypeGenerator.java:165)
	at com.google.devtools.j2objc.gen.TypeGenerator.printDeclarations(TypeGenerator.java:177)
	at com.google.devtools.j2objc.gen.TypeDeclarationGenerator.printSortedDeclarations(TypeDeclarationGenerator.java:652)
	at com.google.devtools.j2objc.gen.TypeDeclarationGenerator.printInnerDeclarations(TypeDeclarationGenerator.java:622)
	at com.google.devtools.j2objc.gen.TypeDeclarationGenerator.generateInitialDeclaration(TypeDeclarationGenerator.java:111)
	at com.google.devtools.j2objc.gen.TypeDeclarationGenerator.generate(TypeDeclarationGenerator.java:87)
	at com.google.devtools.j2objc.gen.TypeDeclarationGenerator.generate(TypeDeclarationGenerator.java:66)
	at com.google.devtools.j2objc.gen.GeneratedType.fromTypeDeclaration(GeneratedType.java:103)
	at com.google.devtools.j2objc.gen.GenerationUnit.addCompilationUnit(GenerationUnit.java:167)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processConvertedTree(TranslationProcessor.java:102)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processCompiledSource(FileProcessor.java:172)
	at com.google.devtools.j2objc.pipeline.FileProcessor.access$000(FileProcessor.java:42)
	at com.google.devtools.j2objc.pipeline.FileProcessor$1.handleParsedUnit(FileProcessor.java:144)
	at com.google.devtools.j2objc.util.JdtParser$1.acceptAST(JdtParser.java:165)
	at j2objc.org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1029)
	at j2objc.org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:636)
	at j2objc.org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:990)
	at com.google.devtools.j2objc.util.JdtParser.parseFiles(JdtParser.java:174)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:152)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInput(FileProcessor.java:96)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:69)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:76)
	at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:139)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:174)

**Comment by hborjaille** [comment]
I've got the same

**Comment by y0ke** [comment]
any updates?

**Comment by ljshj** [comment]
@ex3ndr how to correct  this?

**Comment by hborjaille** [comment]
any changes?

**Comment by lilac** [comment]
Encountered the same issue. Any resolution or workarounds?

**Comment by lilac** [comment]
The issue is resolved by rectifying the number of colons in the objc name to be consistent with the number of args in corresponding java methods.

**Comment by ravindragit** [comment]
@lilac can you please explain it in detail how you solved this ? Do i need to change something in makefile ?
