### ISSUE TITLE
akka-persistence-jdbc_2.11;1.2.1: not found

### ISSUE THREAD

**Issue by udee297** [actorapp/actor-platform#908]
[warn] 	module not found: com.github.dnvriend#akka-persistence-jdbc_2.11;1.2.1
[warn] ==== local: tried
[warn]   /home/j1gsaw/.ivy2/local/com.github.dnvriend/akka-persistence-jdbc_2.11/1.2.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/github/dnvriend/akka-persistence-jdbc_2.11/1.2.1/akka-persistence-jdbc_2.11-1.2.1.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/github/dnvriend/akka-persistence-jdbc_2.11/1.2.1/akka-persistence-jdbc_2.11-1.2.1.pom
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/com/github/dnvriend/akka-persistence-jdbc_2.11/1.2.1/akka-persistence-jdbc_2.11-1.2.1.pom
[info] Resolving com.google.android.gcm#gcm-server;1.0.2 ...
[warn] 	module not found: com.google.android.gcm#gcm-server;1.0.2
[warn] ==== local: tried
[warn]   /home/j1gsaw/.ivy2/local/com.google.android.gcm/gcm-server/1.0.2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/google/android/gcm/gcm-server/1.0.2/gcm-server-1.0.2.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/google/android/gcm/gcm-server/1.0.2/gcm-server-1.0.2.pom
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/com/google/android/gcm/gcm-server/1.0.2/gcm-server-1.0.2.pom
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.github.dnvriend#akka-persistence-jdbc_2.11;1.2.1: not found
[warn] 	:: com.google.android.gcm#gcm-server;1.0.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.github.dnvriend:akka-persistence-jdbc_2.11:1.2.1
[warn] 		  +- im.actor.server:actor-runtime:1.0.3
[warn] 		  +- im.actor.server:actor-core:1.0.3
[warn] 		  +- im.actor.server:actor-session-messages:1.0.3
[warn] 		  +- im.actor.server:actor-rpc-api:1.0.3
[warn] 		  +- im.actor.server:actor-session:1.0.3
[warn] 		  +- im.actor.server:actor-frontend:1.0.3
[warn] 		  +- im.actor.server:actor-server-sdk:1.0.3 (/home/j1gsaw/actor-bootstrap-master/server/build.sbt#L9-10)
[warn] 		  +- actor:actor_2.11:0.1-SNAPSHOT
[warn] 		com.google.android.gcm:gcm-server:1.0.2
[warn] 		  +- im.actor.server:actor-core:1.0.3
[warn] 		  +- im.actor.server:actor-session-messages:1.0.3
[warn] 		  +- im.actor.server:actor-rpc-api:1.0.3
[warn] 		  +- im.actor.server:actor-session:1.0.3
[warn] 		  +- im.actor.server:actor-frontend:1.0.3
[warn] 		  +- im.actor.server:actor-server-sdk:1.0.3 (/home/j1gsaw/actor-bootstrap-master/server/build.sbt#L9-10)
[warn] 		  +- actor:actor_2.11:0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: com.github.dnvriend#akka-persistence-jdbc_2.11;1.2.1: not found
unresolved dependency: com.google.android.gcm#gcm-server;1.0.2: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1439)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1435)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1470)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1468)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1473)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1467)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1490)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1417)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1369)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.github.dnvriend#akka-persistence-jdbc_2.11;1.2.1: not found
[error] unresolved dependency: com.google.android.gcm#gcm-server;1.0.2: not found
[error] Total time: 20 s, completed May 28, 2016 10:42:48 AM

**Comment by udee297** [comment]
seems like all repo links are dead
