### ISSUE TITLE
Android app crashes making a call

### ISSUE THREAD

**Issue by vikingo710** [actorapp/actor-platform#987]
08-28 19:50:49.857 E/AndroidRuntime(21934): FATAL EXCEPTION: PeerConnectionConnectionThread
08-28 19:50:49.857 E/AndroidRuntime(21934): Process: im.actor.cloud, PID: 21934
08-28 19:50:49.857 E/AndroidRuntime(21934): Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
08-28 19:50:49.857 E/AndroidRuntime(21934): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.webrtc.PeerConnection.addStream(org.webrtc.MediaStream)' on a null object reference
08-28 19:50:49.857 E/AndroidRuntime(21934): 	at im.actor.runtime.android.webrtc.AndroidPeerConnection.lambda$addOwnStream$886(AndroidPeerConnection.java:156)
08-28 19:50:49.857 E/AndroidRuntime(21934): 	at im.actor.runtime.android.webrtc.AndroidPeerConnection.access$lambda$2(AndroidPeerConnection.java)
08-28 19:50:49.857 E/AndroidRuntime(21934): 	at im.actor.runtime.android.webrtc.AndroidPeerConnection$$Lambda$3.run(Unknown Source)
08-28 19:50:49.857 E/AndroidRuntime(21934): 	at android.os.Handler.handleCallback(Handler.java:739)
08-28 19:50:49.857 E/AndroidRuntime(21934): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-28 19:50:49.857 E/AndroidRuntime(21934): 	at android.os.Looper.loop(Looper.java:148)
08-28 19:50:49.857 E/AndroidRuntime(21934): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by vikingo710** [comment]
Its working now, maybe was something in the server.
